# Generated by Django 5.1.2 on 2024-12-03 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.bus'),
        ),
        migrations.AddField(
            model_name='seat',
            name='reservation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
