# Generated by Django 5.1.2 on 2024-12-03 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_seat_bus_seat_reservation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_travel', models.DateField()),
                ('departure_time', models.TimeField()),
                ('boarding_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.boardinglocation')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bus')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.destination')),
            ],
        ),
    ]
