# Generated by Django 5.1.2 on 2024-12-06 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_travelschedule_fare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='fare',
        ),
    ]
