# Generated by Django 5.1.2 on 2024-12-07 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_booking_booking_order_id_delete_seatbooking'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seat',
            name='unique_seat_per_bus',
        ),
    ]
